#!/usr/bin/env bash
# Build and run
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Set DEVICE_ID here to avoid doing it in both build and run
DEVICE_ID=${DEVICE_ID:-$("$SCRIPT_DIR/get-device" "device")}
export DEVICE_ID

"$SCRIPT_DIR/build-device" && exec "$SCRIPT_DIR/run-device"
