#!/usr/bin/env bash
# Build the project for a physical device
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

DEVICE_ID=$("$SCRIPT_DIR/get-device" "device")
export DEVICE_ID

exec "$SCRIPT_DIR/build"
