#!/usr/bin/env bash
# Run the IDE
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

PROJECT_FILE="$(fd "xcodeproj$" | head -1)"
open -a Xcode "$PROJECT_FILE" "$@"
