#!/usr/bin/env bash
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

echo >&2 "Installing build tools ..."
TOOLS=(direnv git-lfs)
for tool in "${TOOLS[@]}"; do
    command -v "$tool" &>/dev/null || brew install "$tool"
done
